# Generated by Django 5.0.3 on 2024-04-10 05:32

import django.db.models.deletion
import news.custom_field
import news.helpers
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Name of Category"
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("is_homepage", news.custom_field.CustomBooleanField()),
                (
                    "layout",
                    models.CharField(
                        choices=[("list", "List"), ("grid", "Grid")],
                        default="list",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("ordering", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Category",
            },
        ),
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("ordering", models.IntegerField(default=0)),
                ("link", models.CharField(max_length=250)),
            ],
            options={
                "verbose_name_plural": "Feed",
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("ordering", models.IntegerField(default=0)),
                ("special", news.custom_field.CustomBooleanField()),
                ("content", tinymce.models.HTMLField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=news.helpers.get_file_path
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("publish_date", models.DateTimeField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="news.category"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Article",
            },
        ),
    ]
