'''
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
'''

import os
from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m-3f$t&ni!_9^5elr8^^z7!7k&%lj55(1+v$1=h50qn1_#4uao'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
# By default, INSTALLED_APPS contains the following apps, all of which come with Django:
# django.contrib.admin – The admin site. You’ll use it shortly.
# django.contrib.auth – An authentication system.
# django.contrib.contenttypes – A framework for content types.
# django.contrib.sessions – A session framework.
# django.contrib.messages – A messaging framework.
# django.contrib.staticfiles – A framework for managing static files.
INSTALLED_APPS = [
    'news.apps.NewsConfig',
    'shop.apps.ShopConfig',
    'healthapp.apps.HealthappConfig',
    'account.apps.AccountConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_cleanup.apps.CleanupConfig',
    'django.contrib.humanize',
    'django_extensions',
    'oauth2_provider',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'drf_yasg',
    'tinymce',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'oauth2_provider.middleware.OAuth2TokenMiddleware',
]

CORS_ORIGIN_ALLOW_ALL = True

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            # when the user load website, this will always run
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'news.my_context.items_category_sidebar_menu',
                'news.my_context.items_feed_sidebar_menu',
                'news.my_context.items_article_recent_sidebar_menu',
                'news.my_context.items_article_footer_random_sidebar_menu',
                'news.my_context.items_article_header_trending',
                'news.my_context.items_price_sidebar_coin',
                'news.my_context.items_price_sidebar_gold',
                'shop.my_context.items_category_menu',
                'shop.my_context.item_cart_info_menu'
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'meouptnk@gmail.com'
EMAIL_HOST_PASSWORD = 'afwlwpmubehphhkj'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    'default': {
        'ENGINE' : 'django.db.backends.mysql',
        'NAME': 'django-auth-demo',
        'USER': 'root',
        # 'PASSWORD': 'password',
        'HOST' : 'localhost',
        'PORT': '4306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Ho_Chi_Minh'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR,'static')
STATICFILES_DIRS =[
    os.path.join(BASE_DIR,'static')
]

MEDIA_URL ='/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

AUTH_USER_MODEL = 'account.User'

REST_FRAMEWORK = {
    'NON_FIELD_ERRORS_KEY': 'errors',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated'
    ],
    'DEFAULT_FILTER_BACKENDS' : [ 
        'django_filters.rest_framework.DjangoFilterBackend' 
    ],
    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    # 'PAGE_SIZE': 3,
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=2),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
    # "Bearer <Token>"
}

# SWAGGER_SETTINGS = {
#     'USE_SESSION_AUTH': False,
#     'SECURITY_DEFINITIONS': {
#         'Linh Chi API - Swagger': {
#             'type': 'oauth2',
#             'authorizationUrl': '/o/authorize',
#             'tokenUrl': '/o/token/',
#             'flow': 'accessCode',
#             'scopes': {
#                 'read': 'Read scope',
#                 'write': 'Write scope',
#                 'groups': 'Access to your groups'
#             }
#         }
#     },
#     'OAUTH2_REDIRECT_URL': 'http://localhost:8000/news',
    # 'OAUTH2_CONFIG': {
    #     'clientId': 'FUrOrsKRSDN1su2R15l2RVMNor07PNhqUXhKhlSc',
    #     'clientSecret': 'rHu3UjgpnEavL0T3FAGOR23shtzuRCtC4jMaELqGdhtIQrta2SSyHG5JqlvuUnKbxHaLjszEH9ftDdoncpnI3irtF7LWp2XqWO2Vu0WjV3BKGq8etA1fOw5HzXoYfs00',
    #     'appName': 'mysite'
    # },
# }

# LOGIN_URL = '/admin/login/'
# ID: FUrOrsKRSDN1su2R15l2RVMNor07PNhqUXhKhlSc
# SECRET: rHu3UjgpnEavL0T3FAGOR23shtzuRCtC4jMaELqGdhtIQrta2SSyHG5JqlvuUnKbxHaLjszEH9ftDdoncpnI3irtF7LWp2XqWO2Vu0WjV3BKGq8etA1fOw5HzXoYfs00
# {'access_token': 'Pe9YSHms8oZdMMTAO13LwebUeYhECa', 'expires_in': 36000, 'token_type': 'Bearer', 'scope': 'read write groups'}