# Generated by Django 5.0.3 on 2024-04-10 05:32

import django.db.models.deletion
import shop.custom_field
import shop.helpers
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("ordering", models.IntegerField(default=0)),
                ("special", shop.custom_field.CustomBooleanField()),
                ("publish_date", models.DateTimeField()),
                ("content", tinymce.models.HTMLField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=shop.helpers.get_file_path
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Blog",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Name of Category"
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("is_homepage", shop.custom_field.CustomBooleanField()),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("ordering", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Category",
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Name of Contact"),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("message", models.TextField()),
                ("contacted", shop.custom_field.CustomBooleanFieldContact()),
                ("message_admin", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Contact",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Name of Order"),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=20)),
                ("quantity", models.IntegerField(default=0)),
                (
                    "total",
                    models.DecimalField(decimal_places=0, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("order", "Order"),
                            ("confirm", "Confirm"),
                            ("delivery", "Delivery"),
                            ("finish", "Finish"),
                        ],
                        default="order",
                        max_length=20,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Order",
            },
        ),
        migrations.CreateModel(
            name="PlantingMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Name of Planting method",
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("is_homepage", shop.custom_field.CustomBooleanField()),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("ordering", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Planting method",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("ordering", models.IntegerField(default=0)),
                ("special", shop.custom_field.CustomBooleanField()),
                ("price", models.DecimalField(decimal_places=0, max_digits=10)),
                (
                    "price_sale",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=10, null=True
                    ),
                ),
                (
                    "price_real",
                    models.DecimalField(
                        decimal_places=0, editable=False, max_digits=10
                    ),
                ),
                ("total_sold", models.IntegerField(default=0, editable=False)),
                ("summary", models.TextField()),
                ("content", tinymce.models.HTMLField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=shop.helpers.get_file_path
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.category"
                    ),
                ),
                ("planting_methods", models.ManyToManyField(to="shop.plantingmethod")),
            ],
            options={
                "verbose_name_plural": "Product",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=0, max_digits=10)),
                ("total", models.DecimalField(decimal_places=0, max_digits=10)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.order"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="shop.product"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Order Item",
            },
        ),
    ]
