from django.utils import timezone

BLOGS = [
  {
    "name": "The Ultimate Guide to Indoor Gardening",
    "slug": "the-ultimate-guide-indoor-gardening",
    "status": "published",
    "ordering": 1,
    "special": True,
    "publish_date": timezone.now(),
  },
  {
    "name": "10 Best Houseplants for Beginners",
    "slug": "10-best-houseplants-beginners",
    "status": "published",
    "ordering": 2,
    "special": True,
    "publish_date": timezone.now(),
  },
  {
    "name": "How to Propagate Succulents: A Step-by-Step Guide",
    "slug": "how-to-propagate-succulents-step-by-step",
    "status": "published",
    "ordering": 3,
    "special": True,
    "publish_date": timezone.now(),
  },
  {
    "name": "Creating Your Own Herb Garden at Home",
    "slug": "creating-herb-garden-at-home",
    "status": "published",
    "ordering": 4,
    "special": True,
    "publish_date": timezone.now(),
  },
  {
    "name": "Top 5 Tips for Caring for Your Potted Plants",
    "slug": "tips-caring-potted-plants",
    "status": "published",
    "ordering": 5,
    "special": True,
    "publish_date": timezone.now(),
  },
  {
    "name": "The Benefits of Growing Plants Indoors",
    "slug": "benefits-growing-plants-indoors",
    "status": "published",
    "ordering": 6,
    "special": True,
    "publish_date": timezone.now(),
  },
  {
    "name": "Exploring Different Plant Varieties for Your Garden",
    "slug": "explore-plant-varieties-for-your-garden",
    "status": "published",
    "ordering": 7,
    "special": True,
    "publish_date": timezone.now(),
  },
  {
    "name": "How to Choose the Right Soil for Your Plants",
    "slug": "choose-right-soil-for-your-plants",
    "status": "published",
    "ordering": 8,
    "special": True,
    "publish_date": timezone.now(),
  },
  {
    "name": "Decorating Your Home with Plants: Ideas and Inspiration",
    "slug": "decorate-home-with-plants-ideas",
    "status": "published",
    "ordering": 9,
    "special": True,
    "publish_date": timezone.now(),
  },
  {
    "name": "Common Mistakes to Avoid When Growing Plants",
    "slug": "avoid-mistakes-growing-plants",
    "status": "published",
    "ordering": 10,
    "special": True,
    "publish_date": timezone.now(),
  }
]
